# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbdac9b30a59f1aa8f5071b300c1a363e38d8c8894c24614e5de4c7ae9eb199bcecb2a7fcbb391e2f43d6f84866a0713fd01c2e4f4d1cf334009fe12f735ec78

test:
  secret_key_base: c0f65236aa239818479ed77acc3d208e53e5178037c25b6c29791f2127723c0418bfcacc9f8fe6ea4c09446fa7a8f6f6f2c4415dd005d3ab23e4ab563460083e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
